run_name: "input_mask_no_jump"

player_count: 2

p0_model:
  name: "p0_input_mask_no_jump"
  frames_per_observation: 5
  reaction_delay: 1
  learning_rate: 1e-4

p1_model:
  name: "p1_input_mask_no_jump"
  frames_per_observation: 5
  reaction_delay: 1
  learning_rate: 1e-4


data_path: "../data"
minmax_file: "eval/categorical_less_minmax.json"
count_save: 1

# explore
probability_action: True
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 100
explore_reset: 10
eps_explore_threshold: 0


# reward
reward_gamma: .5
atk_preframes: 2
whiff_reward: 0
reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1
reward_falloff: 25

# training
episode_sample_size: 1
last_episode_only: False
batch_size: 512
epochs: 4
tau: 200

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

input_mask:
  [0, 1, 2, 3, 8, 9, 10, 11, 16, 17, 18, 19, 24, 25, 26, 27, 32, 33, 34, 35, 40, 41, 42, 43]

timer_max: 9999999

log_level: DEBUG

save_model: True



