run_name: "count_shiki_.95_reduc_5f_obs"

p0_model:
  name: "count_v_shiki_.95_reduc_5f_obs"
  frames_per_observation: 2
  reaction_delay: 1
  input_lookback: 6
  learning_rate: 1e-5


p1_model:
  name: "shiki_v_count_.95_reduc_5f_obs"
  frames_per_observation: 2
  reaction_delay: 1
  input_lookback: 6
  learning_rate: 1e-5

data_path: "../data"
minmax_file: "reduced_minmax.json"
count_save: 1

# explore
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 100
no_explore_limit: 10
eps_explore_threshold: -1


# reward
reward_gamma: .95
atk_preframes: 3
whiff_reward: -1000
reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1
reward_falloff: 25

# training
episode_sample_size: 1
last_episode_only: False
batch_size: 512
epochs: 20
tau: 20

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

timer_max: 9999999

log_level: DEBUG

save_model: True



