run_name: "input_lookback_test"

data_path: "../data"
minmax_file: "reduced_minmax.json"
count_save: 1

# eval
frames_per_observation: 1
reaction_delay: 1
input_lookback: 6

# explore
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 100


# reward
hit_preframes: 20
reward_gamma: .8
atk_preframes: 8
whiff_reward: -1000
reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1
reward_falloff: 25

# training
episode_sample_size: 10
learning_rate: 1e-5
last_episode_only: False
batch_size: 512
epochs: 1
tau: 100

# inputs
directions:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

buttons:
  - "a"
  - "b"
  - "c"
  - "d"















timer_max: 9999999

log_level: DEBUG

save_model: True



