run_name: "shiki_v_shiki_transformer"

player_count: 2

p0_model:
  name: "model_delay_debug_p0"
  type: 'rnn'
  hyperparams:
    hidden_dim: 512
    num_layers: 2
  frames_per_observation: 20
  reaction_delay: 5
  learning_rate: 1e-4
  reward_gamma: .5
  full_reward: False
  atk_preframes: 2
  whiff_reward: 0
  reward_columns:
    0:
      "p_0_health": 1
      "p_1_health": -1
  reward_falloff: 25
  input_mask:
  state_features: []


p1_model:
  name: "model_delay_debug_p1"
  type: 'rnn'
  hyperparams:
    hidden_dim: 512
    num_layers: 2
  frames_per_observation: 20
  reaction_delay: 5
  learning_rate: 1e-4
  reward_gamma: .5
  full_reward: False
  atk_preframes: 2
  whiff_reward: 0
  reward_columns:
    0:
      "p_0_health": 1
      "p_1_health": -1
  reward_falloff: 25
  input_mask:
  state_features: []




data_path: "../data"
minmax_file: "eval/no_cat_less_minmax.json"
count_save: 1

# explore
probability_action: False
final_epsilon:  0
initial_epsilon: 0
epsilon_decay: 200
explore_reset: 10
eps_explore_threshold: 0


# training
episode_sample_size: 1
last_episode_only: False
batch_size: 512
epochs: 1
tau: 200

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"


timer_max: 9999

log_level: DEBUG

save_model: True



