run_name: "hot_one_encode"

player_count: 1

p0_model:
  name: "p1_shiki_hot_one_encode"
  frames_per_observation: 5
  reaction_delay: 1
  learning_rate: 1e-4

p1_model:
  name: "blank"
  frames_per_observation: 5
  reaction_delay: 1
  learning_rate: 1e-4


data_path: "../data"
minmax_file: "eval/categorical_less_minmax.json"
count_save: 1

# explore
probability_action: true
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 100
no_explore_limit: 0
explore_reset: 1000
eps_explore_threshold: 0


# reward
reward_gamma: .5
atk_preframes: 2
whiff_reward: 0
reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1
reward_falloff: 25

# training
episode_sample_size: 1
last_episode_only: False
batch_size: 512
epochs: 1
tau: 50

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

timer_max: 9999999

log_level: DEBUG

save_model: True



