run_name: "roa vs shiki"

data_path: "../data"
minmax_file: "reduced_minmax.json"
count_save: 1

# eval
frames_per_observation: 1
reaction_delay: 1
input_lookback: 6

# explore
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 100
no_explore_count: 10
no_explore_min: .05


# reward
hit_preframes: 20
reward_gamma: .8
atk_preframes: 8
whiff_reward: -1000
reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1
reward_falloff: 25

# training
episode_sample_size: 1
learning_rate: 1e-5
last_episode_only: False
batch_size: 512
epochs: 2
tau: 50

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

timer_max: 9999999

log_level: DEBUG

save_model: True



