run_name: "transformer training_test"

player_count: 1

p0_model:
  name: "transformer_frames"
  type: 'transformer'
  hyperparams:
    hidden_dim: 512
    num_layers: 1
    attention_heads: 4
  frames_per_observation: 20
  reaction_delay: 1
  learning_rate: 1e-4
  reward_gamma: .5
  atk_preframes: 2
  whiff_reward: 0
  reward_columns:
    0:
      "p_0_health": 1
      "p_1_health": -1
  reward_falloff: 25
  input_mask:


#p0_model:
#  name: "rnn_test"
#  type: 'rnn'
#  hyperparams:
#    hidden_dim: 512
#    num_layers: 2
#  frames_per_observation: 20
#  reaction_delay: 1
#  learning_rate: 1e-4
#  reward_gamma: .5
#  atk_preframes: 2
#  whiff_reward: 0
#  reward_columns:
#    0:
#      "p_0_health": 1
#      "p_1_health": -1
#  reward_falloff: 25
#  input_mask:

p1_model:
  name: "frame_skip_test_p2"
  type: 'rnn'
  hyperparams:
    hidden_dim: 1024
    num_layers: 2
  frames_per_observation: 20
  reaction_delay: 1
  learning_rate: 1e-4
  reward_gamma: .5
  atk_preframes: 2
  whiff_reward: 0
  reward_columns:
    0:
      "p_0_health": 1
      "p_1_health": -1
  reward_falloff: 25
  input_mask:


data_path: "../data"
minmax_file: "eval/categorical_less_minmax.json"
count_save: 1

# explore
probability_action: False
final_epsilon:  0
initial_epsilon: 1
epsilon_decay: 200
explore_reset: 10
eps_explore_threshold: 0


# training
episode_sample_size: 1
last_episode_only: False
batch_size: 512
epochs: 4
tau: 200

# inputs
directions:
  - ["1","3"]
  - ["2","2"]
  - ["3","1"]
  - ["4","6"]
  - ["5","5"]
  - ["6","4"]
  - ["7","9"]
  - ["8","8"]
  - ["9","7"]

buttons:
  - "a"
  - "b"
  - "c"
  - "d"


timer_max: 9999999

log_level: DEBUG

save_model: True



