run_name: "smooth_reset"
minmax_file: "data/test_minmax.json"
valid_inputs:
  - "2"
  - "4"
  - "8"
  - "6"
  - "a"
  - "b"
  - "c"
  - "d"

model_file:

timer_max: 1000

log_level: DEBUG

save_model: False

