run_name: "no_delay_neg_p1"
minmax_file: "data/new_minmax.json"
valid_inputs:
  - "2"
  - "4"
  - "8"
  - "6"
  - "a"
  - "b"
  - "c"
  - "d"
frames_per_observation: 10
reaction_delay: 1
learning_rate: 1e-5


model_file:

count_save: 20
epochs: 1

timer_max: 9999999

log_level: DEBUG

save_model: True

reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1.5

reward_falloff: 15
