run_name: "smooth_reset"
minmax_file: "data/test_minmax.json"
valid_inputs:
  - "2"
  - "4"
  - "8"
  - "6"
  - "a"
  - "b"
  - "c"
  - "d"

model_file:

count_save: 2

timer_max: 200

log_level: DEBUG

save_model: True

reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1

reward_falloff: 15
