run_name: "smooth_reset"
minmax_file: "data/test_minmax.json"
valid_inputs:
  - "2"
  - "4"
  - "8"
  - "6"
  - "a"
  - "b"
  - "c"
  - "d"
frames_per_observation: 5
reaction_delay: 20
learning_rate: 1e-5


model_file:

count_save: 10
epochs: 20

timer_max: 9999999

log_level: DEBUG

save_model: True

reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1

reward_falloff: 15
