run_name: "random_action_test"
minmax_file: "data/expanded_minmax.json"

directions:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

frames_per_observation: 1
reaction_delay: 20
learning_rate: 1e-5

final_epsilon:  .01
initial_epsilon: .01
epsilon_decay: 2
use_best_action: False


tau: 50
batch_size: 128

count_save: 1
epochs: 10

timer_max: 9999999

log_level: DEBUG

save_model: True

reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1

reward_falloff: 25
