run_name: "input_lookback_test"
minmax_file: "data/reduced_minmax.json"

directions:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

buttons:
  - "a"
  - "b"
  - "c"
  - "d"

frames_per_observation: 1
reaction_delay: 1
input_lookback: 6
learning_rate: .001
hit_preframes: 20
reward_gamma: .8

final_epsilon:  0
initial_epsilon: 0
epsilon_decay: 100
use_best_action: 0

last_episode_only: True
tau: 50
batch_size: 512

count_save: 1
epochs: 1

timer_max: 9999999

log_level: DEBUG

save_model: True

reward_columns:
  0:
    "p_0_health": 1
    "p_1_health": -1
  1:
    "p_0_health": -1
    "p_1_health": 1

reward_falloff: 25
